### ISSUE TITLE
Plugins front page, black area appear below navbar on smaller screens

### ISSUE THREAD

**Issue by PerJensen** [Elgg/community_theme#24]
It's the body background-color that appears. It is added to community_theme to add background-color to the area below the footer.

But the entire body section should not be pushed down, I think it's a bug in aalborg_theme, the float below is apparently redundant:

``` CSS
.elgg-layout-one-sidebar {
    width: 100%;
    float: left;
}
```
